# Generated by Django 5.1.4 on 2024-12-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Event Title')),
                ('description', models.TextField(verbose_name='Event Description')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('capacity', models.IntegerField(verbose_name='Event Capacity')),
                ('category', models.CharField(max_length=50, verbose_name='Event Category')),
                ('image', models.ImageField(blank=True, default='./assets/event_images.default.jpg', null=True, upload_to='event_images/')),
                ('participants', models.IntegerField(default=0, verbose_name='Participants Count')),
                ('date', models.DateTimeField(verbose_name='Event Date')),
                ('location', models.CharField(max_length=255, verbose_name='Event Location')),
            ],
        ),
    ]
